Listen = "localhost:80"
TLS = false
PrivateKey = [ "C:/daten/keys/putty_ed25519.priv.openssh", "C:/daten/keys/putty_2048.priv.openssh" ]
Logfile = ""
Loglevel = "DEBUG"
Logformat = "%{time:2006-01-02T15:04:05.000} %{module}::%{shortfunc} [%{shortfile}] > %{level:.5s} - %{message}"

Tempdir = "c:/temp/bagit"
Basedir = "c:/temp/bagit"
Keydir = "c:/temp/bagit/keys"
DBFolder = "c:/temp/bagit/badger"

# remove temporary files after bagit creation
Cleanup = false

# checksums which need to be created for bagit
Checksum  = ["md5", "sha1", "sha512"]

# rename filenames with characters which should be avoided
FixFilenames = true

# list of pronom id's which should be stored without compression
Nocompress = ["fmt/17", "fmt/353"]  # pdf, tiff

#ingest only stuff
ingestloc = "temp"

[tunnel.main]
    user = "root"
    privatekey = "C:/daten/keys/putty_ed25519.priv.openssh"
    endpoint = "ba14ns21403.fhnw.ch:22"
    [tunnel.main.forward.mysql]
        local = "localhost:3308"
        remote = "v000306.adm.ds.fhnw.ch:3306"

[db]
    #[username[:password]@][protocol[(address)]]/dbname[?param1=value1&...&paramN=valueN]
    dsn = "tbbs:hcpOLPk64DtgNXLR@tcp(localhost:3308)/tbbs?parseTime=true"
    connMaxTimeout = "4h"
    schema = "tbbs"

[[filemap]]
    alias = "c"
    folder = "c:/"

[[filemap]]
    alias = "blah"
    folder = "c:/temp"

[indexer]
    # url to call indexer service [[PATH]] will be replaced with filename
    Url = "http://localhost:8000"
    Checks = ["siegfried", "identify", "ffprobe", "nsrl"]
    #Checks = ["siegfried", "identify", "ffprobe" /*"tika", */, "nsrl"]
